### ISSUE TITLE
Can't add customer on [Create new cart] screen 

### ISSUE THREAD

**Issue by hoa-nx** [VenomAV/EventSourcingCQRS#1]
Dear Andrea Vallotti , 

When i press [Creare] button on [Create new cart] popup , I received error like attach image.
Please help me correct this problem.
![docker-ps](https://user-images.githubusercontent.com/6762312/41508412-5a89cf2e-71f9-11e8-98f6-11de09ed2acc.png)
![add-customer](https://user-images.githubusercontent.com/6762312/41508416-641f2de0-71f9-11e8-9339-903d843f9f4b.png)
![add-customer-error](https://user-images.githubusercontent.com/6762312/41508418-6689fb50-71f9-11e8-80ea-a5c56706e77c.png)

Thank you,

**Comment by VenomAV** [comment]
Hi @thieu-nx ,

it seems that you have some connection issues between eventstore and eventsourcingcqrs containers. I managed to reproduce the exception in the following way:

- starting the whole application from VS
- add some carts using [Create new cart] pop-up
- killing the eventstore container (using docker kill)
- try to add another cart. This give me the same exception as above.

In order to make the connection more robust I changed the creation of the EventStoreConnection in Startup.cs from this
`EventStoreConnection.Create(new Uri("tcp://eventstore:1113"));`
to this
`EventStoreConnection.Create(ConnectionSettings.Create().KeepReconnecting(), new Uri("tcp://eventstore:1113"));
`
Even in this way it did not work. After enabling the verbose log on the EventStore client library, I found out that, if the eventsourcingcqrs container cannot resolve the EventStore container's name through DNS, the client library stops reconnecting no matter how it is configured.
The name resolution issue could happen because docker DNS resolves container names only when they are up and running (I tested it).
To solve your issue you could work on the configurations of the containers in order to ensure the name resolution even if the container are not available (using static IPs and configuring hosts files), or you could modify the application code in order to create a new connection object every time the connection is closed for this reason.

Regards,
Andrea.

**Comment by hoa-nx** [comment]
Dear Andrea Vallotti ,

The problem seems to be solved when i use  : 
 EventStoreConnection.Create(ConnectionSettings.Create().KeepReconnecting(), new Uri("tcp://localhost:1113"));
※eventstore change to localhost.

Thank you for guiding me.

Regards,
Hoa
